apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - podsnapshot.gke.io_crds.yaml
  - runtimeclass.yaml
  - sandbox_namespace.yaml
  - minio.yaml
  - service_account.yaml
  - cluster_role.yaml
  - cluster_role_binding.yaml
  - daemonset.yaml
