{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sandbox-control-plane
  namespace: {{ .Values.systemNamespace | quote }}
  labels:
    {{- include "daytona-sandbox-controller.labels" . | nindent 4 }}
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - sandbox-controller
          - sandbox-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
{{- end }}
