apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox-controller
  namespace: {{ .Values.systemNamespace | quote }}
  labels:
    {{- include "daytona-sandbox-controller.controllerLabels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox-api
  namespace: {{ .Values.systemNamespace | quote }}
  labels:
    {{- include "daytona-sandbox-controller.apiLabels" . | nindent 4 }}
