/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the OtelForwardingConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OtelForwardingConfig{}

// OtelForwardingConfig struct for OtelForwardingConfig
type OtelForwardingConfig struct {
	// OTLP HTTP endpoint for forwarding sandbox telemetry
	Endpoint string `json:"endpoint"`
	// HTTP headers to include when forwarding sandbox telemetry
	Headers              map[string]string `json:"headers"`
	AdditionalProperties map[string]interface{}
}

type _OtelForwardingConfig OtelForwardingConfig

// NewOtelForwardingConfig instantiates a new OtelForwardingConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOtelForwardingConfig(endpoint string, headers map[string]string) *OtelForwardingConfig {
	this := OtelForwardingConfig{}
	this.Endpoint = endpoint
	this.Headers = headers
	return &this
}

// NewOtelForwardingConfigWithDefaults instantiates a new OtelForwardingConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOtelForwardingConfigWithDefaults() *OtelForwardingConfig {
	this := OtelForwardingConfig{}
	return &this
}

// GetEndpoint returns the Endpoint field value
func (o *OtelForwardingConfig) GetEndpoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value
// and a boolean to check if the value has been set.
func (o *OtelForwardingConfig) GetEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Endpoint, true
}

// SetEndpoint sets field value
func (o *OtelForwardingConfig) SetEndpoint(v string) {
	o.Endpoint = v
}

// GetHeaders returns the Headers field value
func (o *OtelForwardingConfig) GetHeaders() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value
// and a boolean to check if the value has been set.
func (o *OtelForwardingConfig) GetHeadersOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Headers, true
}

// SetHeaders sets field value
func (o *OtelForwardingConfig) SetHeaders(v map[string]string) {
	o.Headers = v
}

func (o OtelForwardingConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OtelForwardingConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["endpoint"] = o.Endpoint
	toSerialize["headers"] = o.Headers

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OtelForwardingConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"endpoint",
		"headers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOtelForwardingConfig := _OtelForwardingConfig{}

	err = json.Unmarshal(data, &varOtelForwardingConfig)

	if err != nil {
		return err
	}

	*o = OtelForwardingConfig(varOtelForwardingConfig)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "endpoint")
		delete(additionalProperties, "headers")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOtelForwardingConfig struct {
	value *OtelForwardingConfig
	isSet bool
}

func (v NullableOtelForwardingConfig) Get() *OtelForwardingConfig {
	return v.value
}

func (v *NullableOtelForwardingConfig) Set(val *OtelForwardingConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableOtelForwardingConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableOtelForwardingConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOtelForwardingConfig(val *OtelForwardingConfig) *NullableOtelForwardingConfig {
	return &NullableOtelForwardingConfig{value: val, isSet: true}
}

func (v NullableOtelForwardingConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOtelForwardingConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
