/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the DaytonaConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DaytonaConfiguration{}

// DaytonaConfiguration struct for DaytonaConfiguration
type DaytonaConfiguration struct {
	// Daytona version
	Version string `json:"version"`
	// Proxy template URL
	ProxyTemplateUrl string `json:"proxyTemplateUrl"`
	// Toolbox template URL
	ProxyToolboxUrl string `json:"proxyToolboxUrl"`
	// Default snapshot for sandboxes
	DefaultSnapshot string `json:"defaultSnapshot"`
	// Dashboard URL
	DashboardUrl string `json:"dashboardUrl"`
	// Maximum auto-archive interval in minutes
	MaxAutoArchiveInterval float32 `json:"maxAutoArchiveInterval"`
	// Whether maintenance mode is enabled
	MaintananceMode bool `json:"maintananceMode"`
	// Current environment
	Environment string `json:"environment"`
	// SSH Gateway command
	SshGatewayCommand *string `json:"sshGatewayCommand,omitempty"`
	// Base64 encoded SSH Gateway public key
	SshGatewayPublicKey  *string `json:"sshGatewayPublicKey,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DaytonaConfiguration DaytonaConfiguration

// NewDaytonaConfiguration instantiates a new DaytonaConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDaytonaConfiguration(version string, proxyTemplateUrl string, proxyToolboxUrl string, defaultSnapshot string, dashboardUrl string, maxAutoArchiveInterval float32, maintananceMode bool, environment string) *DaytonaConfiguration {
	this := DaytonaConfiguration{}
	this.Version = version
	this.ProxyTemplateUrl = proxyTemplateUrl
	this.ProxyToolboxUrl = proxyToolboxUrl
	this.DefaultSnapshot = defaultSnapshot
	this.DashboardUrl = dashboardUrl
	this.MaxAutoArchiveInterval = maxAutoArchiveInterval
	this.MaintananceMode = maintananceMode
	this.Environment = environment
	return &this
}

// NewDaytonaConfigurationWithDefaults instantiates a new DaytonaConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDaytonaConfigurationWithDefaults() *DaytonaConfiguration {
	this := DaytonaConfiguration{}
	return &this
}

// GetVersion returns the Version field value
func (o *DaytonaConfiguration) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *DaytonaConfiguration) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *DaytonaConfiguration) SetVersion(v string) {
	o.Version = v
}

// GetProxyTemplateUrl returns the ProxyTemplateUrl field value
func (o *DaytonaConfiguration) GetProxyTemplateUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProxyTemplateUrl
}

// GetProxyTemplateUrlOk returns a tuple with the ProxyTemplateUrl field value
// and a boolean to check if the value has been set.
func (o *DaytonaConfiguration) GetProxyTemplateUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProxyTemplateUrl, true
}

// SetProxyTemplateUrl sets field value
func (o *DaytonaConfiguration) SetProxyTemplateUrl(v string) {
	o.ProxyTemplateUrl = v
}

// GetProxyToolboxUrl returns the ProxyToolboxUrl field value
func (o *DaytonaConfiguration) GetProxyToolboxUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProxyToolboxUrl
}

// GetProxyToolboxUrlOk returns a tuple with the ProxyToolboxUrl field value
// and a boolean to check if the value has been set.
func (o *DaytonaConfiguration) GetProxyToolboxUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProxyToolboxUrl, true
}

// SetProxyToolboxUrl sets field value
func (o *DaytonaConfiguration) SetProxyToolboxUrl(v string) {
	o.ProxyToolboxUrl = v
}

// GetDefaultSnapshot returns the DefaultSnapshot field value
func (o *DaytonaConfiguration) GetDefaultSnapshot() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefaultSnapshot
}

// GetDefaultSnapshotOk returns a tuple with the DefaultSnapshot field value
// and a boolean to check if the value has been set.
func (o *DaytonaConfiguration) GetDefaultSnapshotOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultSnapshot, true
}

// SetDefaultSnapshot sets field value
func (o *DaytonaConfiguration) SetDefaultSnapshot(v string) {
	o.DefaultSnapshot = v
}

// GetDashboardUrl returns the DashboardUrl field value
func (o *DaytonaConfiguration) GetDashboardUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DashboardUrl
}

// GetDashboardUrlOk returns a tuple with the DashboardUrl field value
// and a boolean to check if the value has been set.
func (o *DaytonaConfiguration) GetDashboardUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DashboardUrl, true
}

// SetDashboardUrl sets field value
func (o *DaytonaConfiguration) SetDashboardUrl(v string) {
	o.DashboardUrl = v
}

// GetMaxAutoArchiveInterval returns the MaxAutoArchiveInterval field value
func (o *DaytonaConfiguration) GetMaxAutoArchiveInterval() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.MaxAutoArchiveInterval
}

// GetMaxAutoArchiveIntervalOk returns a tuple with the MaxAutoArchiveInterval field value
// and a boolean to check if the value has been set.
func (o *DaytonaConfiguration) GetMaxAutoArchiveIntervalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxAutoArchiveInterval, true
}

// SetMaxAutoArchiveInterval sets field value
func (o *DaytonaConfiguration) SetMaxAutoArchiveInterval(v float32) {
	o.MaxAutoArchiveInterval = v
}

// GetMaintananceMode returns the MaintananceMode field value
func (o *DaytonaConfiguration) GetMaintananceMode() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.MaintananceMode
}

// GetMaintananceModeOk returns a tuple with the MaintananceMode field value
// and a boolean to check if the value has been set.
func (o *DaytonaConfiguration) GetMaintananceModeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaintananceMode, true
}

// SetMaintananceMode sets field value
func (o *DaytonaConfiguration) SetMaintananceMode(v bool) {
	o.MaintananceMode = v
}

// GetEnvironment returns the Environment field value
func (o *DaytonaConfiguration) GetEnvironment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value
// and a boolean to check if the value has been set.
func (o *DaytonaConfiguration) GetEnvironmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Environment, true
}

// SetEnvironment sets field value
func (o *DaytonaConfiguration) SetEnvironment(v string) {
	o.Environment = v
}

// GetSshGatewayCommand returns the SshGatewayCommand field value if set, zero value otherwise.
func (o *DaytonaConfiguration) GetSshGatewayCommand() string {
	if o == nil || IsNil(o.SshGatewayCommand) {
		var ret string
		return ret
	}
	return *o.SshGatewayCommand
}

// GetSshGatewayCommandOk returns a tuple with the SshGatewayCommand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaytonaConfiguration) GetSshGatewayCommandOk() (*string, bool) {
	if o == nil || IsNil(o.SshGatewayCommand) {
		return nil, false
	}
	return o.SshGatewayCommand, true
}

// HasSshGatewayCommand returns a boolean if a field has been set.
func (o *DaytonaConfiguration) HasSshGatewayCommand() bool {
	if o != nil && !IsNil(o.SshGatewayCommand) {
		return true
	}

	return false
}

// SetSshGatewayCommand gets a reference to the given string and assigns it to the SshGatewayCommand field.
func (o *DaytonaConfiguration) SetSshGatewayCommand(v string) {
	o.SshGatewayCommand = &v
}

// GetSshGatewayPublicKey returns the SshGatewayPublicKey field value if set, zero value otherwise.
func (o *DaytonaConfiguration) GetSshGatewayPublicKey() string {
	if o == nil || IsNil(o.SshGatewayPublicKey) {
		var ret string
		return ret
	}
	return *o.SshGatewayPublicKey
}

// GetSshGatewayPublicKeyOk returns a tuple with the SshGatewayPublicKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaytonaConfiguration) GetSshGatewayPublicKeyOk() (*string, bool) {
	if o == nil || IsNil(o.SshGatewayPublicKey) {
		return nil, false
	}
	return o.SshGatewayPublicKey, true
}

// HasSshGatewayPublicKey returns a boolean if a field has been set.
func (o *DaytonaConfiguration) HasSshGatewayPublicKey() bool {
	if o != nil && !IsNil(o.SshGatewayPublicKey) {
		return true
	}

	return false
}

// SetSshGatewayPublicKey gets a reference to the given string and assigns it to the SshGatewayPublicKey field.
func (o *DaytonaConfiguration) SetSshGatewayPublicKey(v string) {
	o.SshGatewayPublicKey = &v
}

func (o DaytonaConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DaytonaConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	toSerialize["proxyTemplateUrl"] = o.ProxyTemplateUrl
	toSerialize["proxyToolboxUrl"] = o.ProxyToolboxUrl
	toSerialize["defaultSnapshot"] = o.DefaultSnapshot
	toSerialize["dashboardUrl"] = o.DashboardUrl
	toSerialize["maxAutoArchiveInterval"] = o.MaxAutoArchiveInterval
	toSerialize["maintananceMode"] = o.MaintananceMode
	toSerialize["environment"] = o.Environment
	if !IsNil(o.SshGatewayCommand) {
		toSerialize["sshGatewayCommand"] = o.SshGatewayCommand
	}
	if !IsNil(o.SshGatewayPublicKey) {
		toSerialize["sshGatewayPublicKey"] = o.SshGatewayPublicKey
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DaytonaConfiguration) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version",
		"proxyTemplateUrl",
		"proxyToolboxUrl",
		"defaultSnapshot",
		"dashboardUrl",
		"maxAutoArchiveInterval",
		"maintananceMode",
		"environment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDaytonaConfiguration := _DaytonaConfiguration{}

	err = json.Unmarshal(data, &varDaytonaConfiguration)

	if err != nil {
		return err
	}

	*o = DaytonaConfiguration(varDaytonaConfiguration)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "version")
		delete(additionalProperties, "proxyTemplateUrl")
		delete(additionalProperties, "proxyToolboxUrl")
		delete(additionalProperties, "defaultSnapshot")
		delete(additionalProperties, "dashboardUrl")
		delete(additionalProperties, "maxAutoArchiveInterval")
		delete(additionalProperties, "maintananceMode")
		delete(additionalProperties, "environment")
		delete(additionalProperties, "sshGatewayCommand")
		delete(additionalProperties, "sshGatewayPublicKey")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDaytonaConfiguration struct {
	value *DaytonaConfiguration
	isSet bool
}

func (v NullableDaytonaConfiguration) Get() *DaytonaConfiguration {
	return v.value
}

func (v *NullableDaytonaConfiguration) Set(val *DaytonaConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableDaytonaConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableDaytonaConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDaytonaConfiguration(val *DaytonaConfiguration) *NullableDaytonaConfiguration {
	return &NullableDaytonaConfiguration{value: val, isSet: true}
}

func (v NullableDaytonaConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDaytonaConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
